#!/bin/bash

MPLBACKEND=Agg python -c "import matplotlib.pyplot"  # Build font cache.

# Install extension that supports '%matplotlib widget'.
jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager
jupyter labextension install --no-build jupyter-matplotlib
# We deferred building above (--no-build) to do it just once here.
jupyter lab build
